export type ContentType = "text" | "url" | "file";

export interface User {
  id: string;
  name: string;
  email: string;
  image: string | null;
  isPro: boolean;
}

export interface ItemType {
  id: string;
  name: string;
  icon: string;
  color: string;
  isSystem: boolean;
  route: string;
}

export interface Item {
  id: string;
  title: string;
  contentType: ContentType;
  content: string | null;
  url: string | null;
  fileUrl: string | null;
  fileName: string | null;
  fileSize: number | null;
  description: string | null;
  language: string | null;
  isFavorite: boolean;
  isPinned: boolean;
  tags: string[];
  userId: string;
  itemTypeId: string;
  collectionIds: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Collection {
  id: string;
  name: string;
  description: string | null;
  isFavorite: boolean;
  defaultTypeId: string | null;
  userId: string;
  itemIds: string[];
  createdAt: Date;
  updatedAt: Date;
}

export const currentUser: User = {
  id: "user_1",
  name: "Demo User",
  email: "danielaEM@example.com",
  image: null,
  isPro: false,
};

export const itemTypes: ItemType[] = [
  {
    id: "type_snippet",
    name: "Snippet",
    icon: "Code",
    color: "#3b82f6",
    isSystem: true,
    route: "/items/snippets",
  },
  {
    id: "type_prompt",
    name: "Prompt",
    icon: "Sparkles",
    color: "#8b5cf6",
    isSystem: true,
    route: "/items/prompts",
  },
  {
    id: "type_command",
    name: "Command",
    icon: "Terminal",
    color: "#f97316",
    isSystem: true,
    route: "/items/commands",
  },
  {
    id: "type_note",
    name: "Note",
    icon: "StickyNote",
    color: "#fde047",
    isSystem: true,
    route: "/items/notes",
  },
  {
    id: "type_file",
    name: "File",
    icon: "File",
    color: "#6b7280",
    isSystem: true,
    route: "/items/files",
  },
  {
    id: "type_image",
    name: "Image",
    icon: "Image",
    color: "#ec4899",
    isSystem: true,
    route: "/items/images",
  },
  {
    id: "type_link",
    name: "Link",
    icon: "Link",
    color: "#10b981",
    isSystem: true,
    route: "/items/links",
  },
];

export const collections: Collection[] = [
  {
    id: "col_react_patterns",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    defaultTypeId: "type_snippet",
    userId: "user_1",
    itemIds: [
      "item_use_auth_hook",
      "item_use_debounce",
      "item_error_boundary",
      "item_react_docs_link",
      "item_component_template",
      "item_use_local_storage",
      "item_theme_context_provider",
      "item_cn_utility",
    ],
    createdAt: new Date("2026-01-02"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "col_python_snippets",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    defaultTypeId: "type_snippet",
    userId: "user_1",
    itemIds: ["item_python_decorator", "item_async_fetch", "item_requirements_txt"],
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-04-22"),
  },
  {
    id: "col_context_files",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    defaultTypeId: "type_file",
    userId: "user_1",
    itemIds: ["item_project_context_md", "item_coding_standards_md"],
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-05-20"),
  },
  {
    id: "col_interview_prep",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    defaultTypeId: "type_note",
    userId: "user_1",
    itemIds: [
      "item_use_auth_hook",
      "item_api_error_handling",
      "item_system_design_notes",
      "item_leetcode_link",
      "item_interview_prompt",
    ],
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-05-18"),
  },
  {
    id: "col_git_commands",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    defaultTypeId: "type_command",
    userId: "user_1",
    itemIds: ["item_git_rebase", "item_git_cheatsheet"],
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "col_ai_prompts",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    defaultTypeId: "type_prompt",
    userId: "user_1",
    itemIds: [
      "item_interview_prompt",
      "item_code_review_prompt",
      "item_refactor_snippet",
      "item_prompt_guide_md",
    ],
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-05-25"),
  },
  {
    id: "col_ai_workflows",
    name: "AI Workflows",
    description: "AI prompts and workflow automations",
    isFavorite: false,
    defaultTypeId: "type_prompt",
    userId: "user_1",
    itemIds: [
      "item_aiwf_code_review",
      "item_aiwf_doc_gen",
      "item_aiwf_refactor",
    ],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "col_devops",
    name: "DevOps",
    description: "Infrastructure and deployment resources",
    isFavorite: false,
    defaultTypeId: "type_snippet",
    userId: "user_1",
    itemIds: [
      "item_devops_dockerfile",
      "item_devops_deploy_cmd",
      "item_devops_docker_docs",
      "item_devops_gh_actions_docs",
    ],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "col_terminal_commands",
    name: "Terminal Commands",
    description: "Useful shell commands for everyday development",
    isFavorite: false,
    defaultTypeId: "type_command",
    userId: "user_1",
    itemIds: [
      "item_term_git_log_graph",
      "item_term_docker_ps",
      "item_term_lsof_port",
      "item_term_npm_outdated",
    ],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "col_design_resources",
    name: "Design Resources",
    description: "UI/UX resources and references",
    isFavorite: false,
    defaultTypeId: "type_link",
    userId: "user_1",
    itemIds: [
      "item_design_tailwind",
      "item_design_shadcn",
      "item_design_material",
      "item_design_lucide",
    ],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
];

export const items: Item[] = [
  {
    id: "item_use_auth_hook",
    title: "useAuth Hook",
    contentType: "text",
    content:
      "export function useAuth() {\n  const [user, setUser] = useState(null);\n  // ...\n  return { user, login, logout };\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Custom authentication hook for React applications",
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_react_patterns", "col_interview_prep"],
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-05-15"),
  },
  {
    id: "item_api_error_handling",
    title: "API Error Handling Pattern",
    contentType: "text",
    content:
      "async function fetchWithRetry(url, options, retries = 3) {\n  // exponential backoff\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Fetch wrapper with exponential backoff retry logic",
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    tags: ["api", "error-handling", "retry"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_interview_prep"],
    createdAt: new Date("2026-01-12"),
    updatedAt: new Date("2026-01-12"),
  },
  {
    id: "item_use_debounce",
    title: "useDebounce Hook",
    contentType: "text",
    content:
      "export function useDebounce<T>(value: T, delay: number): T {\n  // ...\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Debounce a value with configurable delay",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "hooks", "performance"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-02-03"),
    updatedAt: new Date("2026-02-03"),
  },
  {
    id: "item_error_boundary",
    title: "Error Boundary Component",
    contentType: "text",
    content: "class ErrorBoundary extends React.Component {\n  // ...\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Reusable error boundary with fallback UI",
    language: "tsx",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "error-handling"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-02-10"),
  },
  {
    id: "item_react_docs_link",
    title: "React Documentation",
    contentType: "url",
    content: null,
    url: "https://react.dev",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Official React documentation",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["react", "docs"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-01-20"),
  },
  {
    id: "item_component_template",
    title: "Component Template.tsx",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/component-template.tsx",
    fileName: "component-template.tsx",
    fileSize: 1240,
    description: "Starter template for new React components",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["react", "template"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-01"),
  },
  {
    id: "item_python_decorator",
    title: "Timing Decorator",
    contentType: "text",
    content:
      "def timeit(func):\n    def wrapper(*args, **kwargs):\n        # ...\n    return wrapper",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Measure function execution time",
    language: "python",
    isFavorite: false,
    isPinned: false,
    tags: ["python", "decorator"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_python_snippets"],
    createdAt: new Date("2026-02-15"),
    updatedAt: new Date("2026-02-15"),
  },
  {
    id: "item_async_fetch",
    title: "Async HTTP Fetch",
    contentType: "text",
    content:
      "async def fetch(url: str) -> dict:\n    async with aiohttp.ClientSession() as session:\n        # ...",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Async HTTP request with aiohttp",
    language: "python",
    isFavorite: false,
    isPinned: false,
    tags: ["python", "async", "http"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_python_snippets"],
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-03-05"),
  },
  {
    id: "item_requirements_txt",
    title: "requirements.txt",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/requirements.txt",
    fileName: "requirements.txt",
    fileSize: 320,
    description: "Standard Python project dependencies",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["python", "deps"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_python_snippets"],
    createdAt: new Date("2026-03-10"),
    updatedAt: new Date("2026-03-10"),
  },
  {
    id: "item_project_context_md",
    title: "project-context.md",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/project-context.md",
    fileName: "project-context.md",
    fileSize: 4820,
    description: "Project overview for AI agents",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "context"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_context_files"],
    createdAt: new Date("2026-01-22"),
    updatedAt: new Date("2026-05-20"),
  },
  {
    id: "item_coding_standards_md",
    title: "coding-standards.md",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/coding-standards.md",
    fileName: "coding-standards.md",
    fileSize: 2150,
    description: "Team coding standards",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "context", "standards"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_context_files"],
    createdAt: new Date("2026-01-25"),
    updatedAt: new Date("2026-04-18"),
  },
  {
    id: "item_system_design_notes",
    title: "System Design Notes",
    contentType: "text",
    content: "# System Design\n\n- Load balancing\n- Caching strategies\n- ...",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Notes on common system design topics",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["interview", "system-design"],
    userId: "user_1",
    itemTypeId: "type_note",
    collectionIds: ["col_interview_prep"],
    createdAt: new Date("2026-02-20"),
    updatedAt: new Date("2026-05-01"),
  },
  {
    id: "item_leetcode_link",
    title: "LeetCode",
    contentType: "url",
    content: null,
    url: "https://leetcode.com",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Coding interview practice",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["interview", "practice"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_interview_prep"],
    createdAt: new Date("2026-02-22"),
    updatedAt: new Date("2026-02-22"),
  },
  {
    id: "item_interview_prompt",
    title: "Mock Interview Prompt",
    contentType: "text",
    content:
      "You are a senior engineer conducting a technical interview. Ask me one question at a time...",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "AI prompt for mock interviews",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["interview", "prompt", "ai"],
    userId: "user_1",
    itemTypeId: "type_prompt",
    collectionIds: ["col_interview_prep", "col_ai_prompts"],
    createdAt: new Date("2026-03-12"),
    updatedAt: new Date("2026-03-12"),
  },
  {
    id: "item_git_rebase",
    title: "Interactive rebase",
    contentType: "text",
    content: "git rebase -i HEAD~5",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Squash, reorder, or edit the last 5 commits",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["git", "rebase"],
    userId: "user_1",
    itemTypeId: "type_command",
    collectionIds: ["col_git_commands"],
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-02-05"),
  },
  {
    id: "item_git_cheatsheet",
    title: "git-cheatsheet.md",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/git-cheatsheet.md",
    fileName: "git-cheatsheet.md",
    fileSize: 1820,
    description: "Quick reference for everyday git commands",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["git", "reference"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_git_commands"],
    createdAt: new Date("2026-02-08"),
    updatedAt: new Date("2026-04-30"),
  },
  {
    id: "item_code_review_prompt",
    title: "Code Review Prompt",
    contentType: "text",
    content:
      "Review the following code for correctness, performance, and readability. Be specific...",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "AI prompt for thorough code reviews",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["prompt", "review"],
    userId: "user_1",
    itemTypeId: "type_prompt",
    collectionIds: ["col_ai_prompts"],
    createdAt: new Date("2026-03-15"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "item_refactor_snippet",
    title: "Refactor helper snippet",
    contentType: "text",
    content: "// Common refactor patterns reference",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Snippet used alongside refactor prompts",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["refactor"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_ai_prompts"],
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-04-01"),
  },
  {
    id: "item_prompt_guide_md",
    title: "prompt-guide.md",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/prompt-guide.md",
    fileName: "prompt-guide.md",
    fileSize: 3200,
    description: "Guide for writing effective AI prompts",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["prompt", "guide"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_ai_prompts"],
    createdAt: new Date("2026-04-05"),
    updatedAt: new Date("2026-05-25"),
  },
  // React Patterns additions
  {
    id: "item_use_local_storage",
    title: "useLocalStorage Hook",
    contentType: "text",
    content:
      "export function useLocalStorage<T>(key: string, initialValue: T) {\n  const [value, setValue] = useState<T>(() => {\n    if (typeof window === \"undefined\") return initialValue;\n    try {\n      const stored = window.localStorage.getItem(key);\n      return stored ? (JSON.parse(stored) as T) : initialValue;\n    } catch {\n      return initialValue;\n    }\n  });\n\n  useEffect(() => {\n    window.localStorage.setItem(key, JSON.stringify(value));\n  }, [key, value]);\n\n  return [value, setValue] as const;\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Persist state to localStorage with SSR-safe initialization",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "hooks", "localstorage"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_theme_context_provider",
    title: "Theme Context Provider",
    contentType: "text",
    content:
      "type ThemeContextValue = {\n  theme: \"light\" | \"dark\";\n  toggle: () => void;\n};\n\nconst ThemeContext = createContext<ThemeContextValue | null>(null);\n\nexport function ThemeProvider({ children }: { children: ReactNode }) {\n  const [theme, setTheme] = useState<\"light\" | \"dark\">(\"dark\");\n  const toggle = () => setTheme((t) => (t === \"dark\" ? \"light\" : \"dark\"));\n  return (\n    <ThemeContext.Provider value={{ theme, toggle }}>\n      {children}\n    </ThemeContext.Provider>\n  );\n}\n\nexport function useTheme() {\n  const ctx = useContext(ThemeContext);\n  if (!ctx) throw new Error(\"useTheme must be used within ThemeProvider\");\n  return ctx;\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Typed Context provider + hook pattern with safety check",
    language: "tsx",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "context", "pattern"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_cn_utility",
    title: "cn() classnames utility",
    contentType: "text",
    content:
      "import { clsx, type ClassValue } from \"clsx\";\nimport { twMerge } from \"tailwind-merge\";\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs));\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Merge Tailwind class names without conflicts",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["utility", "tailwind"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  // AI Workflows
  {
    id: "item_aiwf_code_review",
    title: "Code Review Workflow",
    contentType: "text",
    content:
      "You are a senior code reviewer. Analyze the following diff and report:\n1. Correctness issues (bugs, edge cases)\n2. Performance concerns\n3. Readability problems\n4. Security risks\n\nFor each finding include: severity (critical/major/minor), the affected lines, and a concrete suggested fix.\n\nDIFF:\n{{diff}}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Structured prompt for reviewing a diff with severity-tagged findings",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "prompt", "review"],
    userId: "user_1",
    itemTypeId: "type_prompt",
    collectionIds: ["col_ai_workflows"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_aiwf_doc_gen",
    title: "Documentation Generation",
    contentType: "text",
    content:
      "Generate documentation for the following code. Include:\n- One-line summary\n- Parameter descriptions (with types)\n- Return value\n- Thrown errors / failure modes\n- One realistic usage example\n\nMatch the existing doc style of the project. Do not invent behavior that isn't in the code.\n\nCODE:\n{{code}}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Prompt for generating API docs from a function or module",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "prompt", "docs"],
    userId: "user_1",
    itemTypeId: "type_prompt",
    collectionIds: ["col_ai_workflows"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_aiwf_refactor",
    title: "Refactoring Assistant",
    contentType: "text",
    content:
      "Refactor the following code to improve readability and maintainability without changing observable behavior. Constraints:\n- Preserve the public API (exported names, signatures)\n- Do not introduce new dependencies\n- Keep the file under {{maxLines}} lines\n\nReturn the refactored code, then a short bullet list explaining each significant change.\n\nCODE:\n{{code}}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Behavior-preserving refactor with constraints and change log",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "prompt", "refactor"],
    userId: "user_1",
    itemTypeId: "type_prompt",
    collectionIds: ["col_ai_workflows"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  // DevOps
  {
    id: "item_devops_dockerfile",
    title: "Multi-stage Node Dockerfile",
    contentType: "text",
    content:
      "# syntax=docker/dockerfile:1\nFROM node:20-alpine AS deps\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\n\nFROM node:20-alpine AS runner\nWORKDIR /app\nENV NODE_ENV=production\nCOPY --from=deps /app/node_modules ./node_modules\nCOPY . .\nEXPOSE 3000\nCMD [\"node\", \"server.js\"]",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Multi-stage production Dockerfile for a Node service",
    language: "dockerfile",
    isFavorite: false,
    isPinned: false,
    tags: ["docker", "ci-cd"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_devops"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_devops_deploy_cmd",
    title: "SSH deploy + restart",
    contentType: "text",
    content:
      "ssh deploy@prod.example.com 'cd /srv/app && git pull --ff-only && npm ci --omit=dev && npm run build && pm2 restart app --update-env'",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Pull, build, and restart the app over SSH via PM2",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["deploy", "ssh", "pm2"],
    userId: "user_1",
    itemTypeId: "type_command",
    collectionIds: ["col_devops"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_devops_docker_docs",
    title: "Docker Documentation",
    contentType: "url",
    content: null,
    url: "https://docs.docker.com/",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Official Docker documentation",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["docker", "docs"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_devops"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_devops_gh_actions_docs",
    title: "GitHub Actions Documentation",
    contentType: "url",
    content: null,
    url: "https://docs.github.com/en/actions",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Reference for GitHub Actions workflows and CI/CD",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ci-cd", "github", "docs"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_devops"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  // Terminal Commands
  {
    id: "item_term_git_log_graph",
    title: "Pretty git log graph",
    contentType: "text",
    content:
      "git log --oneline --graph --decorate --all",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Compact branch graph across all refs",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["git", "log"],
    userId: "user_1",
    itemTypeId: "type_command",
    collectionIds: ["col_terminal_commands"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_term_docker_ps",
    title: "Readable docker ps",
    contentType: "text",
    content:
      "docker ps --format 'table {{.Names}}\\t{{.Image}}\\t{{.Status}}\\t{{.Ports}}'",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Container list as a clean table",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["docker"],
    userId: "user_1",
    itemTypeId: "type_command",
    collectionIds: ["col_terminal_commands"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_term_lsof_port",
    title: "Find process on a port",
    contentType: "text",
    content:
      "lsof -i :3000 -sTCP:LISTEN -n -P",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Show the process listening on port 3000",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["process", "ports"],
    userId: "user_1",
    itemTypeId: "type_command",
    collectionIds: ["col_terminal_commands"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_term_npm_outdated",
    title: "List outdated top-level deps",
    contentType: "text",
    content:
      "npm outdated --depth=0",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Show outdated direct dependencies only",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["npm", "deps"],
    userId: "user_1",
    itemTypeId: "type_command",
    collectionIds: ["col_terminal_commands"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  // Design Resources
  {
    id: "item_design_tailwind",
    title: "Tailwind CSS Docs",
    contentType: "url",
    content: null,
    url: "https://tailwindcss.com/docs",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Tailwind CSS utility reference",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["css", "tailwind", "docs"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_design_resources"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_design_shadcn",
    title: "shadcn/ui",
    contentType: "url",
    content: null,
    url: "https://ui.shadcn.com/",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Copy-and-paste component library built on Radix + Tailwind",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["components", "ui"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_design_resources"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_design_material",
    title: "Material Design 3",
    contentType: "url",
    content: null,
    url: "https://m3.material.io/",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Google's design system reference",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["design-system"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_design_resources"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
  {
    id: "item_design_lucide",
    title: "Lucide Icons",
    contentType: "url",
    content: null,
    url: "https://lucide.dev/icons",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Open-source icon library used across the app",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["icons"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_design_resources"],
    createdAt: new Date("2026-05-29"),
    updatedAt: new Date("2026-05-29"),
  },
];
