export type ContentType = "text" | "url" | "file";

export interface User {
  id: string;
  name: string;
  email: string;
  image: string | null;
  isPro: boolean;
}

export interface ItemType {
  id: string;
  name: string;
  icon: string;
  color: string;
  isSystem: boolean;
  route: string;
}

export interface Item {
  id: string;
  title: string;
  contentType: ContentType;
  content: string | null;
  url: string | null;
  fileUrl: string | null;
  fileName: string | null;
  fileSize: number | null;
  description: string | null;
  language: string | null;
  isFavorite: boolean;
  isPinned: boolean;
  tags: string[];
  userId: string;
  itemTypeId: string;
  collectionIds: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Collection {
  id: string;
  name: string;
  description: string | null;
  isFavorite: boolean;
  defaultTypeId: string | null;
  userId: string;
  itemIds: string[];
  createdAt: Date;
  updatedAt: Date;
}

export const currentUser: User = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  image: null,
  isPro: true,
};

export const itemTypes: ItemType[] = [
  {
    id: "type_snippet",
    name: "Snippet",
    icon: "Code",
    color: "#3b82f6",
    isSystem: true,
    route: "/items/snippets",
  },
  {
    id: "type_prompt",
    name: "Prompt",
    icon: "Sparkles",
    color: "#8b5cf6",
    isSystem: true,
    route: "/items/prompts",
  },
  {
    id: "type_command",
    name: "Command",
    icon: "Terminal",
    color: "#f97316",
    isSystem: true,
    route: "/items/commands",
  },
  {
    id: "type_note",
    name: "Note",
    icon: "StickyNote",
    color: "#fde047",
    isSystem: true,
    route: "/items/notes",
  },
  {
    id: "type_file",
    name: "File",
    icon: "File",
    color: "#6b7280",
    isSystem: true,
    route: "/items/files",
  },
  {
    id: "type_image",
    name: "Image",
    icon: "Image",
    color: "#ec4899",
    isSystem: true,
    route: "/items/images",
  },
  {
    id: "type_link",
    name: "Link",
    icon: "Link",
    color: "#10b981",
    isSystem: true,
    route: "/items/links",
  },
];

export const collections: Collection[] = [
  {
    id: "col_react_patterns",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    defaultTypeId: "type_snippet",
    userId: "user_1",
    itemIds: [
      "item_use_auth_hook",
      "item_use_debounce",
      "item_error_boundary",
      "item_react_docs_link",
      "item_component_template",
    ],
    createdAt: new Date("2026-01-02"),
    updatedAt: new Date("2026-05-15"),
  },
  {
    id: "col_python_snippets",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    defaultTypeId: "type_snippet",
    userId: "user_1",
    itemIds: ["item_python_decorator", "item_async_fetch", "item_requirements_txt"],
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-04-22"),
  },
  {
    id: "col_context_files",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    defaultTypeId: "type_file",
    userId: "user_1",
    itemIds: ["item_project_context_md", "item_coding_standards_md"],
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-05-20"),
  },
  {
    id: "col_interview_prep",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    defaultTypeId: "type_note",
    userId: "user_1",
    itemIds: [
      "item_use_auth_hook",
      "item_api_error_handling",
      "item_system_design_notes",
      "item_leetcode_link",
      "item_interview_prompt",
    ],
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-05-18"),
  },
  {
    id: "col_git_commands",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    defaultTypeId: "type_command",
    userId: "user_1",
    itemIds: ["item_git_rebase", "item_git_cheatsheet"],
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "col_ai_prompts",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    defaultTypeId: "type_prompt",
    userId: "user_1",
    itemIds: [
      "item_interview_prompt",
      "item_code_review_prompt",
      "item_refactor_snippet",
      "item_prompt_guide_md",
    ],
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-05-25"),
  },
];

export const items: Item[] = [
  {
    id: "item_use_auth_hook",
    title: "useAuth Hook",
    contentType: "text",
    content:
      "export function useAuth() {\n  const [user, setUser] = useState(null);\n  // ...\n  return { user, login, logout };\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Custom authentication hook for React applications",
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_react_patterns", "col_interview_prep"],
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-05-15"),
  },
  {
    id: "item_api_error_handling",
    title: "API Error Handling Pattern",
    contentType: "text",
    content:
      "async function fetchWithRetry(url, options, retries = 3) {\n  // exponential backoff\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Fetch wrapper with exponential backoff retry logic",
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    tags: ["api", "error-handling", "retry"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_interview_prep"],
    createdAt: new Date("2026-01-12"),
    updatedAt: new Date("2026-01-12"),
  },
  {
    id: "item_use_debounce",
    title: "useDebounce Hook",
    contentType: "text",
    content:
      "export function useDebounce<T>(value: T, delay: number): T {\n  // ...\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Debounce a value with configurable delay",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "hooks", "performance"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-02-03"),
    updatedAt: new Date("2026-02-03"),
  },
  {
    id: "item_error_boundary",
    title: "Error Boundary Component",
    contentType: "text",
    content: "class ErrorBoundary extends React.Component {\n  // ...\n}",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Reusable error boundary with fallback UI",
    language: "tsx",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "error-handling"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-02-10"),
  },
  {
    id: "item_react_docs_link",
    title: "React Documentation",
    contentType: "url",
    content: null,
    url: "https://react.dev",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Official React documentation",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["react", "docs"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-01-20"),
  },
  {
    id: "item_component_template",
    title: "Component Template.tsx",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/component-template.tsx",
    fileName: "component-template.tsx",
    fileSize: 1240,
    description: "Starter template for new React components",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["react", "template"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_react_patterns"],
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-01"),
  },
  {
    id: "item_python_decorator",
    title: "Timing Decorator",
    contentType: "text",
    content:
      "def timeit(func):\n    def wrapper(*args, **kwargs):\n        # ...\n    return wrapper",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Measure function execution time",
    language: "python",
    isFavorite: false,
    isPinned: false,
    tags: ["python", "decorator"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_python_snippets"],
    createdAt: new Date("2026-02-15"),
    updatedAt: new Date("2026-02-15"),
  },
  {
    id: "item_async_fetch",
    title: "Async HTTP Fetch",
    contentType: "text",
    content:
      "async def fetch(url: str) -> dict:\n    async with aiohttp.ClientSession() as session:\n        # ...",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Async HTTP request with aiohttp",
    language: "python",
    isFavorite: false,
    isPinned: false,
    tags: ["python", "async", "http"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_python_snippets"],
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-03-05"),
  },
  {
    id: "item_requirements_txt",
    title: "requirements.txt",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/requirements.txt",
    fileName: "requirements.txt",
    fileSize: 320,
    description: "Standard Python project dependencies",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["python", "deps"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_python_snippets"],
    createdAt: new Date("2026-03-10"),
    updatedAt: new Date("2026-03-10"),
  },
  {
    id: "item_project_context_md",
    title: "project-context.md",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/project-context.md",
    fileName: "project-context.md",
    fileSize: 4820,
    description: "Project overview for AI agents",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "context"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_context_files"],
    createdAt: new Date("2026-01-22"),
    updatedAt: new Date("2026-05-20"),
  },
  {
    id: "item_coding_standards_md",
    title: "coding-standards.md",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/coding-standards.md",
    fileName: "coding-standards.md",
    fileSize: 2150,
    description: "Team coding standards",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "context", "standards"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_context_files"],
    createdAt: new Date("2026-01-25"),
    updatedAt: new Date("2026-04-18"),
  },
  {
    id: "item_system_design_notes",
    title: "System Design Notes",
    contentType: "text",
    content: "# System Design\n\n- Load balancing\n- Caching strategies\n- ...",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Notes on common system design topics",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["interview", "system-design"],
    userId: "user_1",
    itemTypeId: "type_note",
    collectionIds: ["col_interview_prep"],
    createdAt: new Date("2026-02-20"),
    updatedAt: new Date("2026-05-01"),
  },
  {
    id: "item_leetcode_link",
    title: "LeetCode",
    contentType: "url",
    content: null,
    url: "https://leetcode.com",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Coding interview practice",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["interview", "practice"],
    userId: "user_1",
    itemTypeId: "type_link",
    collectionIds: ["col_interview_prep"],
    createdAt: new Date("2026-02-22"),
    updatedAt: new Date("2026-02-22"),
  },
  {
    id: "item_interview_prompt",
    title: "Mock Interview Prompt",
    contentType: "text",
    content:
      "You are a senior engineer conducting a technical interview. Ask me one question at a time...",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "AI prompt for mock interviews",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["interview", "prompt", "ai"],
    userId: "user_1",
    itemTypeId: "type_prompt",
    collectionIds: ["col_interview_prep", "col_ai_prompts"],
    createdAt: new Date("2026-03-12"),
    updatedAt: new Date("2026-03-12"),
  },
  {
    id: "item_git_rebase",
    title: "Interactive rebase",
    contentType: "text",
    content: "git rebase -i HEAD~5",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Squash, reorder, or edit the last 5 commits",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["git", "rebase"],
    userId: "user_1",
    itemTypeId: "type_command",
    collectionIds: ["col_git_commands"],
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-02-05"),
  },
  {
    id: "item_git_cheatsheet",
    title: "git-cheatsheet.md",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/git-cheatsheet.md",
    fileName: "git-cheatsheet.md",
    fileSize: 1820,
    description: "Quick reference for everyday git commands",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["git", "reference"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_git_commands"],
    createdAt: new Date("2026-02-08"),
    updatedAt: new Date("2026-04-30"),
  },
  {
    id: "item_code_review_prompt",
    title: "Code Review Prompt",
    contentType: "text",
    content:
      "Review the following code for correctness, performance, and readability. Be specific...",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "AI prompt for thorough code reviews",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["prompt", "review"],
    userId: "user_1",
    itemTypeId: "type_prompt",
    collectionIds: ["col_ai_prompts"],
    createdAt: new Date("2026-03-15"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "item_refactor_snippet",
    title: "Refactor helper snippet",
    contentType: "text",
    content: "// Common refactor patterns reference",
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    description: "Snippet used alongside refactor prompts",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["refactor"],
    userId: "user_1",
    itemTypeId: "type_snippet",
    collectionIds: ["col_ai_prompts"],
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-04-01"),
  },
  {
    id: "item_prompt_guide_md",
    title: "prompt-guide.md",
    contentType: "file",
    content: null,
    url: null,
    fileUrl: "https://r2.example.com/files/prompt-guide.md",
    fileName: "prompt-guide.md",
    fileSize: 3200,
    description: "Guide for writing effective AI prompts",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["prompt", "guide"],
    userId: "user_1",
    itemTypeId: "type_file",
    collectionIds: ["col_ai_prompts"],
    createdAt: new Date("2026-04-05"),
    updatedAt: new Date("2026-05-25"),
  },
];
